In [1]:
import pandas as pd 
import numpy as np
import pickle as p
import tensorflow as tf
from tensorflow.keras.models import load_model

WARNING:tensorflow:From c:\Users\chouh\Desktop\Deerp Learning\venv\Lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

In [2]:
model= load_model('model.h5')

WARNING:tensorflow:From c:\Users\chouh\Desktop\Deerp Learning\venv\Lib\site-packages\keras\src\backend.py:1398: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

In [3]:
with open ('label_gender.pkl', 'rb') as file:
    label_encoder_gender = p.load(file)

In [4]:
with open('one_hot_geo.pkl', 'rb') as file:
    one_hot_geo = p.load(file)

In [5]:
with open ('scaler.pkl', 'rb') as file:
    scaler = p.load(file)

In [6]:
#  Sample data 
input_data = {

'CreditScore':600,

'Geography': 'France',

'Gender': 'Male',

'Age': 40,

'Tenure': 3,

'Balance':60000,

'NumOfProducts': 2,

'HasCrCard':1,

'IsActiveMember': 1,

'EstimatedSalary': 50000

}

In [7]:
geo_encoded = one_hot_geo.transform([[input_data['Geography']]]).toarray()

c:\Users\chouh\Desktop\Deerp Learning\venv\Lib\site-packages\sklearn\utils\validation.py:2830: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

In [8]:
geo_encoded

array([[1., 0., 0.]])

In [9]:
geo_df = pd.DataFrame(geo_encoded, columns=one_hot_geo.get_feature_names_out(['Geography']))

In [10]:
geo_df

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [11]:
input_df = pd.DataFrame([input_data])

In [12]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,Male,40,3,60000,2,1,1,50000

In [13]:
input_df['Gender'] = label_encoder_gender.transform(input_df['Gender'])

In [14]:
input_df

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,France,1,40,3,60000,2,1,1,50000

In [15]:
input_df.drop(['Geography'], axis=1, inplace=True)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,600,1,40,3,60000,2,1,1,50000

In [16]:
df = pd.concat([input_df, geo_df], axis=1)

In [17]:
df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,1,40,3,60000,2,1,1,50000,1.0,0.0,0.0

In [18]:
input_scaled = scaler.transform(df)
input_scaled

array([[-0.53598516,  0.91324755,  0.10479359, -0.69539349, -0.25781119,
         0.80843615,  0.64920267,  0.97481699, -0.87683221,  1.00150113,
        -0.57946723, -0.57638802]])

In [19]:
prediction = model.predict(input_scaled)
prediction

1/1 [==============================] - 0s 212ms/step

array([[0.0412241]], dtype=float32)

In [20]:
prediction[0][0]   # 0 leave 1 stay

0.0412241

In [21]:
if prediction[0][0] > 0.5:
    print("The customer is likely to leave.")

else:
    print("The customer is likely to stay.")

The customer is likely to stay.